module.exports = {
  siteMetadata: {
    htmlLang: 'en',
    contentLang: 'en-us',
    title: 'indiegamedevelopment.org',
    titleTemplate: 'Indie game development knowledge base: %s',
    description: 'Indie game development knowledge base',
    siteUrl: 'https://gatbsy-theme-help-center.netlify.app',
    siteName: 'Indie game development knowledge base',
    logoUrl: '/images/logo2.png',
    logoLabel: '',
    searchText: 'Search',
    faviconUrl: '/images/favicon2.png',
    socialSharingImageUrl: '/images/social-sharing-preview.png',
    twitter: '@patangcc',
    facebookUrl: 'https://www.facebook.com/patang.cc',
    ctaButtonText: 'Get updates',
    ctaButtonUrl: '/',
    linkText: '',
    linkUrl: 'https://gatbsy-theme-help-center.netlify.app',
    headline: 'Indie game development knowledge base',
    footerText: 'Home',
    footerUrl: '/',
    googleTagManagerId: '',
    googleAnalyticsMeasurementId: '',
  },
  plugins: ['gatsby-plugin-typescript', '@mlent/gatsby-theme-help-center', `gatsby-plugin-netlify-cms`],
};
