backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - name: page
    label: Page
    folder: pages
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: author, label: Author }
      - { name: categories, label: Categories, widget: list }
      - { name: date, label: Date, widget: date, required: true }
      - { name: tags, label: Tags, widget: list }
      - { name: relatedArticles, label: Related Articles, widget: list }
      - { name: body, label: Body, widget: markdown }
